# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_nian_wechat äº¬ä¸œç‚¸å¹´å…½å°ç¨‹åºğŸ§¨ 

on:
  workflow_dispatch:
  schedule:
    - cron: '50 0 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_nian_wechat
jobs:
  Build-Nodejs-and-Scripts:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: ç­¾å…¥ä»“åº“
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“å­˜ Action
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package.json') }} # ä½¿ç”¨ package-lock.json çš„ Hash ä½œä¸ºç¼“å­˜çš„ keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      
      - name: 'è¿è¡Œ äº¬ä¸œç‚¸å¹´å…½å°ç¨‹åºğŸ§¨'
        run: | 
          cd Scripts
          npm install
          node jd_nian_wechat.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          JD_BEAN_STOP: ${{secrets.JD_BEAN_STOP}} #è‡ªå®šä¹‰å»¶è¿Ÿç­¾åˆ°,å•ä½æ¯«ç§’. é»˜è®¤åˆ†æ‰¹å¹¶å‘æ— å»¶è¿Ÿ. å»¶è¿Ÿä½œç”¨äºæ¯ä¸ªç­¾åˆ°æ¥å£, å¦‚å¡«å…¥å»¶è¿Ÿåˆ™åˆ‡æ¢é¡ºåºç­¾åˆ°(è€—æ—¶è¾ƒé•¿)
          JD_BEAN_SIGN_STOP_NOTIFY: ${{secrets.JD_BEAN_SIGN_STOP_NOTIFY}}
          JD_BEAN_SIGN_NOTIFY_SIMPLE: ${{secrets.JD_BEAN_SIGN_NOTIFY_SIMPLE}}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS }}
          MARKET_REWARD_NOTIFY: ${{ secrets.MARKET_REWARD_NOTIFY }}
          JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY }}
          JD_JOY_REWARD_NAME: ${{ secrets.JD_JOY_REWARD_NAME }}
